hostname='localhost'
username= 'root'
password= ''
database= 'quiz_game'
port=3306
app_base_url='http://localhost/tpfinal_mvc'
smtp_host='localhost'
smtp_username=''
smtp_password=''
smtp_port='1025'
smtp_encryption=''
mail_from='no-reply@arcade.local'
mail_from_name='Arcade de Desafíos'

; Para enviar correos reales, configura un SMTP real, por ejemplo:
; smtp_host='smtp.gmail.com'
; smtp_port='587'
; smtp_username='tu-correo@gmail.com'
; smtp_password='tu-app-password'
; smtp_encryption='tls'
; mail_from='tu-correo@gmail.com'